### ISSUE TITLE
Corrigir bug de duplicação de id ao criar um novo selo

### ISSUE THREAD

**Issue by alessandrofeitoza** [secultce/mapacultural#225]
# **Corrigir bug de duplicação de id ao criar um novo selo**

## **WHAT**
Precisamos encontrar o problema na inserção do primeiro Selo.

## **WHY**
Quando iniciamos o **Mapas** pela primeira vez, toda primeira tentativa de inserção de um Selo acaba nos gerando um erro, no entanto esse erro só acontece na primeira tentativa.

```json
{"error":true,"message":"An exception occurred while executing a query: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint \"seal_pkey\"\nDETAIL:  Key (id)=(1) already exists."}<br />
<b>Fatal error</b>:  Uncaught Doctrine\ORM\Exception\EntityManagerClosed: The EntityManager is closed. in /var/www/vendor/doctrine/orm/lib/Doctrine/ORM/Exception/EntityManagerClosed.php:11
Stack trace:
#0 /var/www/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(877): Doctrine\ORM\Exception\EntityManagerClosed::create()
#1 /var/www/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(663): Doctrine\ORM\EntityManager-&gt;errorIfClosed()
#2 /var/www/src/core/Entity.php(874): Doctrine\ORM\EntityManager-&gt;persist(Object(MapasCulturais\Entities\PermissionCachePending))
#3 /var/www/src/core/App.php(1912): MapasCulturais\Entity-&gt;save(true)
#4 /var/www/src/core/App.php(466): MapasCulturais\App-&gt;persistPCachePendingQueue()
#5 /var/www/html/index.php(13): MapasCulturais\App-&gt;run()
#6 /var/www/dev/router.php(35): include_once('/var/www/html/i...')
#7 {main}
  thrown in <b>/var/www/vendor/doctrine/orm/lib/Doctrine/ORM/Exception/EntityManagerClosed.php</b> on line <b>11</b><br />
```

---

## **ADDITIONAL INFO**
Caso queira reproduzir esse erro, basta resetar o banco de dados, abrir o console requests e tentar inserir um selo, no primeiro selo terá um erro 500.

---

**Comment by henriquelopeslima** [comment]
Para resolver esse probema eu precisei alterar a sequência da propriedade id, no arquivo db-updates.php, que é uma espécie de migration. Eu optei por não alterar o dump.sql por não ser uma boa prática.
